// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/chat/completions": {
            "post": {
                "description": "OpenAI-совместимая генерация ответа. При включённом RAG в system подмешиваются фрагменты из базы.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat completions",
                "parameters": [
                    {
                        "description": "Запрос",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ReqChatCompletion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResChatCompletion"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/embeddings": {
            "get": {
                "description": "Векторное представление текста (POST JSON или GET query).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "embeddings"
                ],
                "summary": "Embeddings",
                "parameters": [
                    {
                        "description": "Тело (POST)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/types.ReqEmbeddings"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Модель",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Текст",
                        "name": "input",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResEmbeddings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            },
            "post": {
                "description": "Векторное представление текста (POST JSON или GET query).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "embeddings"
                ],
                "summary": "Embeddings",
                "parameters": [
                    {
                        "description": "Тело (POST)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/types.ReqEmbeddings"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Модель",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Текст",
                        "name": "input",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResEmbeddings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/models": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Список моделей",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResModelsList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/models/{model}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Модель по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID модели",
                        "name": "model",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ModelObject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/rag/documents": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rag"
                ],
                "summary": "Список документов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResRAGDocuments"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            },
            "post": {
                "description": "Индексирует content или файл по path на сервере.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rag"
                ],
                "summary": "Индексация документа (JSON)",
                "parameters": [
                    {
                        "description": "Документ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ReqRAGIngest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResRAGIngest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/rag/documents/scan": {
            "post": {
                "description": "Индексирует файлы из каталогов RAG.AutoIngest в конфиге.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rag"
                ],
                "summary": "Сканирование каталогов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResRAGScan"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/rag/documents/upload": {
            "post": {
                "description": "Multipart upload: PDF, DOCX, TXT и др. — конвертация и индексация.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rag"
                ],
                "summary": "Загрузка файла",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Файл",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название документа",
                        "name": "title",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResRAGIngest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/rag/documents/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rag"
                ],
                "summary": "Документ по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID документа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Document"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "rag"
                ],
                "summary": "Удалить документ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID документа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/rag/query": {
            "post": {
                "description": "Гибридный поиск (вектор + полнотекстовый) по проиндексированным документам.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rag"
                ],
                "summary": "Поиск по RAG",
                "parameters": [
                    {
                        "description": "Запрос",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ReqRAGQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResRAGQuery"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            }
        },
        "/v1/rag/reindex-embeddings": {
            "post": {
                "description": "Пересчитывает embedding для всех чанков (после смены префиксов search_document/search_query).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rag"
                ],
                "summary": "Пересчёт эмбеддингов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ResRAGReindex"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/types.OpenAIErrorBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "store.ChunkResult": {
            "type": "object",
            "properties": {
                "chunk_id": {
                    "type": "string"
                },
                "chunk_index": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "document_id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object"
                },
                "score": {
                    "type": "number"
                },
                "source_path": {
                    "type": "string"
                },
                "text_rank": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "vector_rank": {
                    "type": "integer"
                }
            }
        },
        "store.Document": {
            "type": "object",
            "properties": {
                "chunk_count": {
                    "type": "integer"
                },
                "content_hash": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object"
                },
                "source_path": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "types.Choice": {
            "type": "object",
            "properties": {
                "delta": {
                    "$ref": "#/definitions/types.Message"
                },
                "finish_reason": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "message": {
                    "$ref": "#/definitions/types.Message"
                }
            }
        },
        "types.Embedding": {
            "type": "object",
            "properties": {
                "embedding": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "index": {
                    "type": "integer"
                }
            }
        },
        "types.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "types.ModelObject": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "owned_by": {
                    "type": "string"
                }
            }
        },
        "types.OpenAIErrorBody": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/types.OpenAIErrorDetail"
                }
            }
        },
        "types.OpenAIErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "param": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.RAGFragment": {
            "type": "object",
            "properties": {
                "chunk_index": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "source_path": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "types.RAGInfo": {
            "type": "object",
            "properties": {
                "chunks_used": {
                    "type": "integer"
                },
                "fragments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.RAGFragment"
                    }
                },
                "titles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "types.ReqChatCompletion": {
            "type": "object",
            "properties": {
                "max_tokens": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Message"
                    }
                },
                "model": {
                    "type": "string"
                },
                "prompt": {
                    "type": "string"
                },
                "rag_top_k": {
                    "type": "integer"
                },
                "seed": {
                    "type": "integer"
                },
                "stream": {
                    "type": "boolean"
                },
                "temperature": {
                    "type": "number"
                },
                "top_p": {
                    "type": "number"
                },
                "use_rag": {
                    "description": "nil → из конфига RAG.UseInChatCompletions (по умолчанию true)",
                    "type": "boolean"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "types.ReqEmbeddings": {
            "type": "object",
            "required": [
                "input"
            ],
            "properties": {
                "input": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "types.ReqRAGIngest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object"
                },
                "path": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "types.ReqRAGQuery": {
            "type": "object",
            "required": [
                "query"
            ],
            "properties": {
                "query": {
                    "type": "string"
                },
                "top_k": {
                    "type": "integer"
                }
            }
        },
        "types.ResChatCompletion": {
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Choice"
                    }
                },
                "created": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "rag": {
                    "$ref": "#/definitions/types.RAGInfo"
                },
                "usage": {
                    "$ref": "#/definitions/types.Usage"
                }
            }
        },
        "types.ResEmbeddings": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Embedding"
                    }
                },
                "model": {
                    "type": "string"
                }
            }
        },
        "types.ResModelsList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ModelObject"
                    }
                },
                "object": {
                    "type": "string"
                }
            }
        },
        "types.ResRAGDocuments": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.Document"
                    }
                }
            }
        },
        "types.ResRAGIngest": {
            "type": "object",
            "properties": {
                "document": {
                    "$ref": "#/definitions/store.Document"
                }
            }
        },
        "types.ResRAGQuery": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.ChunkResult"
                    }
                }
            }
        },
        "types.ResRAGReindex": {
            "type": "object",
            "properties": {
                "reindexed_chunks": {
                    "type": "integer"
                }
            }
        },
        "types.ResRAGScan": {
            "type": "object",
            "properties": {
                "ingested": {
                    "type": "integer"
                }
            }
        },
        "types.Usage": {
            "type": "object",
            "properties": {
                "completion_tokens": {
                    "type": "integer"
                },
                "prompt_tokens": {
                    "type": "integer"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "llama-cpp-gpt-api",
	Description:      "OpenAI-совместимый HTTP API (chat, embeddings, models) и RAG поверх PostgreSQL/pgvector.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
